# This theme uses colors I got from the despacio.vim colorscheme.

array set ::pd_colors {
canvas_fill "#262626"
canvas_text_cursor "#dfaf00"
gop_box "white"
obj_box_text "#875f5f"
msg_box_text "#5f8787"
comment "#585858"
selected "#dfaf00"
obj_box_outline_broken "#ff875f"
obj_box_outline "white"
msg_box_outline "white"
msg_box_fill "#262626"
obj_box_fill "#262626"
signal_cord "#87af87"
msg_cord "white"
msg_iolet "white"
signal_iolet "#87af87"
graph_outline "white"
selection_rectangle "#dfaf00"
txt_highlight "white"
graph_text "#c6c6c6"
array_name "#dfaf87"
array_values "#87afaf"
atom_box_fill "#262626"
atom_box_text "#d78700"
atom_box_label "white"
atom_box_outline "white"
text_window_fill "#262626"
text_window_text "hotpink"
text_window_highlight "white"
text_window_cursor "#dfaf00"
pdwindow_fill "#000000"
pdwindow_fatal_text "#af5f5f"
pdwindow_fatal_highlight "#262626"
pdwindow_error_text "#d75f5f"
pdwindow_post_text "#5f8787"
pdwindow_debug_text "#af875f"
helpbrowser_fill "#000"
helpbrowser_text "#87afaf"
helpbrowser_highlight "#dfaf00"
}
set ::pd_colors(txt_highlight_front) $::pd_colors(selected)
set ::pd_colors(msg_iolet_border) $::pd_colors(msg_cord)
set ::pd_colors(signal_iolet_border) $::pd_colors(signal_cord)
